version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80" # Map host port 3001 to container port 80
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000